#ifndef INCLUDED_KERNEL_FS_MBR_SYSTEM_IDS_H
#define INCLUDED_KERNEL_FS_MBR_SYSTEM_IDS_H


#define MBR_SYS_NTFS 0x07
#define MBR_SYS_LINUX_NATIVE 0x83
#define MBR_SYS_EXT 0x83
#define MBR_SYS_GPT 0xEE

#endif